image:
  repository: eclipse-mosquitto
  tag: 2.0.20@sha256:8b396cec28cd5e8e1a3aba1d9abdbddd42c454c80f703e77c1bec56e152fa54e
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 1883
        targetPort: 1883
  websockets:
    enabled: true
    ports:
      websockets:
        enabled: true
        port: 443
        targetPort: 443

ingresses:
  enabled: true
  className: "nginx"
  annotations: 
    nginx.ingress.kubernetes.io/enable-cors: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/websocket-services: "example-mqtt-broker"
  hosts:
    - host: mqttbroker.factory-x.catena-x.net
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - mqttbroker.factory-x.catena-x.net
  
auth:
  enabled: true
  users:
    - username: admin
      password: $7$101$NSDvLEXHsxbaFRRA$wNhHa/60GCxSMrt9z/g4g4clw1IcVmymp6er4f+7QDLtGuo9/yzF79DaEkVz7NIntW7SthfX/QHucBAjqamvuw==
      acl:
        - topic: "#"
          access: readwrite
websockets:
  # -- By enabling this, an additional listener with protocol websockets is added in the mosquitto config.
  enabled: true
configmap:
  config:
    enabled: true
    data:
      mosquitto.conf: |
        listener {{ .Values.service.main.ports.main.targetPort }}
        {{- if .Values.websockets.enabled }}
        listener {{ .Values.service.websockets.ports.websockets.targetPort }}
        protocol websockets
        {{- end }}
        {{- if .Values.auth.enabled }}
        allow_anonymous false
        {{- else }}
        allow_anonymous true
        {{- end }}
        {{- if .Values.persistence.data.enabled }}
        persistence true
        persistence_location {{ .Values.persistence.data.mountPath }}
        autosave_interval 1800
        {{- end }}
        {{- if .Values.persistence.configinc.enabled }}
        include_dir {{ .Values.persistence.configinc.mountPath }}
        {{- end }}
persistence:
  data:
    enabled: true
    mountPath: "/mosquitto/data"
  configinc:
    enabled: true
    mountPath: "/mosquitto/configinc"
  mosquitto-config:
    enabled: true
    mountPath: "/mosquitto/config/mosquitto.conf"
    subPath: "mosquitto.conf"
    type: configmap
    objectName: config
portal:
  open:
    enabled: false
